services:
  nginx_stores_chrelyonly:
    image: nginx:alpine    # 使用nginx最新镜像
    container_name: nginx
    volumes:
      - ${VOLUME_PATH}/public:/usr/share/nginx/html  # 将public目录挂载到nginx的html目录
      - ${VOLUME_PATH}/dev-chrelyonly/nginx.conf:/etc/nginx/nginx.conf  # 配置自定义的nginx配置文件
    ports:
      - "9080:80"  # 映射本地80端口到容器的80端口
    networks:
      - chrelyonly-network  # 使用相同的网络与其它服务通信

networks:
  chrelyonly-network:  # 定义自定义网络
    driver: bridge  # 使用默认的 bridge 网络驱动
