services:
  api-project-ui-app:
    image: nginx:alpine    # 使用nginx最新镜像
    container_name: api-project-ui-app
    volumes:
      - /www/dk_project/dk_app/api-project-ui-app/app/public:/usr/share/nginx/html  # 将public目录挂载到nginx的html目录
      - /www/dk_project/dk_app/api-project-ui-app/app/nginx.conf:/etc/nginx/nginx.conf  # 配置自定义的nginx配置文件
    ports:
      - "9080:80"  # 映射本地80端口到容器的80端口
    working_dir: /app
    networks:
      - my-network

networks:
  my-network:
    name: wechat-api
    enable_ipv6: true
    driver: bridge
